name: nexus
version: 1.0.0+1
publish_to: none
description: Welcome to the world of nexus.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  bloc: 8.1.4
  cached_network_image: 3.3.1
  collection: 1.18.0
  dartz: 0.10.1
  dio: 5.4.3+1
  event_bus: 2.0.0
  flutter_bloc: 8.1.6
  flutter_cache_manager: 3.3.2
  flutter_keyboard_visibility: 6.0.0
  flutter_native_splash: 2.4.0
  flutter_screenutil: 5.9.0
  flutter_secure_storage: 9.0.0
  flutter_svg: 2.0.10+1
  get_it: 7.7.0
  get_storage: 2.1.1
  google_sign_in: 6.2.1
  injectable: 2.4.2
  lottie: 3.1.0
  network_logger: 1.0.4
  permission_handler: 11.3.1
  pretty_dio_logger: 1.3.1
  visibility_detector: 0.4.0+2
  flutter_chat_ui: ^1.6.15
  get: 4.6.6
  fluttertoast: ^8.2.8
  flutter: 
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^8.0.3
  flutter_chat_types: ^3.6.2
  http: '>=0.13.6 <2.0.0'
  image_picker: ^1.1.1
  intl: ^0.19.0
  mime: ^1.0.5
  open_filex: ^4.4.0
  path_provider: ^2.1.3
  uuid: ^4.5.0
  sidebarx: ^0.17.1
  google_sign_in_web: ^0.12.4+2



dev_dependencies: 
  analyzer: 6.4.1
  build_runner: 2.4.9
  flutter_gen_runner: 5.4.0
  freezed: 2.5.2
  injectable_generator: 2.6.1
  json_serializable: 6.8.0
  lints: 3.0.0
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  integration_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/
    - assets/messages.json
  fonts: 
    - family: IBMPlexSans
      fonts: 
        - asset: fonts/IBM/IBMPlexSans-Bold.ttf
        - asset: fonts/IBM/IBMPlexSans-Light.ttf
        - asset: fonts/IBM/IBMPlexSans-Medium.ttf
        - asset: fonts/IBM/IBMPlexSans-Regular.ttf
        - asset: fonts/IBM/IBMPlexSans-SemiBold.ttf
        - asset: fonts/IBM/IBMPlexSans-ExtraLight.ttf
        - asset: fonts/IBM/IBMPlexSans-Thin.ttf
        - asset: fonts/IBM/IBMPlexSans-BoldItalic.ttf
        - asset: fonts/IBM/IBMPlexSans-LightItalic.ttf
        - asset: fonts/IBM/IBMPlexSans-MediumItalic.ttf
        - asset: fonts/IBM/IBMPlexSans-RegularItalic.ttf
        - asset: fonts/IBM/IBMPlexSans-SemiBoldItalic.ttf
        - asset: fonts/IBM/IBMPlexSans-ExtraLightItalic.ttf
        - asset: fonts/IBM/IBMPlexSans-ThinItalic.ttf
    - family: Swear
      fonts: 
        - asset: fonts/Swear/SwearDisplay-Black.otf
        - asset: fonts/Swear/SwearDisplay-BlackCilati.otf
        - asset: fonts/Swear/SwearDisplay-BlackItalic.otf
        - asset: fonts/Swear/SwearDisplay-Bold.otf
        - asset: fonts/Swear/SwearDisplay-BoldCilati.otf
        - asset: fonts/Swear/SwearDisplay-BoldItalic.otf
        - asset: fonts/Swear/SwearDisplay-Cilati.otf
        - asset: fonts/Swear/SwearDisplay-Italic.otf
        - asset: fonts/Swear/SwearDisplay-Light.otf
        - asset: fonts/Swear/SwearDisplay-LightCilati.otf
        - asset: fonts/Swear/SwearDisplay-LightItalic.otf
        - asset: fonts/Swear/SwearDisplay-Medium.otf
        - asset: fonts/Swear/SwearDisplay-MediumCilati.otf
        - asset: fonts/Swear/SwearDisplay-MediumItalic.otf
        - asset: fonts/Swear/SwearDisplay-Regular.otf
        - asset: fonts/Swear/SwearDisplay-Thin.otf
        - asset: fonts/Swear/SwearDisplay-ThinCilati.otf
        - asset: fonts/Swear/SwearDisplay-ThinItalic.otf
    - family: Roboto
      fonts: 
        - asset: fonts/Roboto/RobotoCondensed-Italic-VariableFont_wght.ttf
        - asset: fonts/Roboto/RobotoCondensed-VariableFont_wght.ttf
  uses-material-design: true

