import 'package:flutter_screenutil/flutter_screenutil.dart';

class Dimens {
  const Dimens._();

  static final double fontSize4 = 4.sp;
  static final double fontSize6 = 6.sp;
  static final double fontSize8 = 8.sp;
  static final double fontSize9 = 9.sp;
  static final double fontSize10 = 10.sp;
  static final double fontSize11 = 11.sp;
  static final double fontSize12 = 12.sp;
  static final double fontSize12_5 = 12.5.sp;
  static final double fontSize13 = 13.sp;
  static final double fontSize14 = 14.sp;
  static final double fontSize14_5 = 14.5.sp;
  static final double fontSize15 = 15.sp;
  static final double fontSize16 = 16.sp;
  static final double fontSize17 = 17.sp;
  static final double fontSize18 = 18.sp;
  static final double fontSize19 = 19.sp;
  static final double fontSize20 = 20.sp;
  static final double fontSize21 = 21.sp;
  static final double fontSize22 = 22.sp;
  static final double fontSize23 = 23.sp;
  static final double fontSize24 = 24.sp;
  static final double fontSize25 = 25.sp;
  static final double fontSize26 = 26.sp;
  static final double fontSize27 = 27.sp;
  static final double fontSize28 = 28.sp;
  static final double fontSize30 = 30.sp;
  static final double fontSize32 = 32.sp;
  static final double fontSize33 = 33.sp;
  static final double fontSize34 = 34.sp;
  static final double fontSize35 = 35.sp;
  static final double fontSize36 = 36.sp;
  static final double fontSize37 = 37.sp;
  static final double fontSize38 = 38.sp;
  static final double fontSize40 = 40.sp;
  static final double fontSize42 = 42.sp;
  static final double fontSize44 = 44.sp;
  static final double fontSize46 = 46.sp;
  static final double fontSize48 = 48.sp;
  static final double fontSize124 = 124.sp;
  static final double fontSize64 = 64.sp;
  static final double fontSize54 = 54.sp;
  static final double fontSize72 = 72.sp;
  static final double fontSize70 = 70.sp;
  static final double fontSize52 = 52.sp;
  static final double fontSize47 = 47.sp;
  static final double fontSize50 = 50.sp;
  static final double fontSize49 = 49.sp;
  static final double fontSize62 = 62.sp;
}
